### ISSUE TITLE
memory free fail after [make]

### ISSUE THREAD

**Issue by Park-Hyung-Joo** [RTimothyEdwards/open_pdks#218]
![mem_fail_after_make](https://user-images.githubusercontent.com/67187317/154413168-342285a8-51d1-4745-b4c4-70baa31e34a3.PNG)
![mem_fail_after_install](https://user-images.githubusercontent.com/67187317/154413203-1c731424-de0d-410e-8fcd-ca20f9b38c29.PNG)

# memory manage issue
during [make], Vmmem takes more than 25Gb of main memory and it still takes even after [sudo make install] finished

**Comment by RTimothyEdwards** [comment]
I can't say what Vmmem is doing;  For Linux systems, all memory for a process is handled by the process and released when the process ends.  On my system, I do not believe that open_pdks takes more than 8GB or so, probably less, most of which is caused by the SRAM library because magic wants to read the GDS for all four SRAM macros at the same time.  If the SRAM library is not installed, then the memory overhead should be very small.  I've never tried the installation on Windows---I assume you're doing this in WSL?

**Comment by Park-Hyung-Joo** [comment]
Yes, I installed them on WSL2 on Windows10. I haven't tried on Linux yet. If it has no matter on your Linux system, does it have no matter with CentOS? Actually, WSL2 is just a test case.

**Comment by RTimothyEdwards** [comment]
It has never been an issue on any Linux system that I am aware of.

**Comment by Park-Hyung-Joo** [comment]
I see thank you
