### ISSUE TITLE
Magic Version Not Listed

### ISSUE THREAD

**Issue by donn** [RTimothyEdwards/open_pdks#219]
There's no version of magic listed recommended to build open_pdks.

Please include this information somewhere.

**Comment by donn** [comment]
Preferably in something parseable.

**Comment by RTimothyEdwards** [comment]
@donn :  See `sky130/magic/sky130.tech` line 26:  `requires magic-8.3.260`.
This is the minimum version of magic required to build a usable version of open_pdks.
However, I should probably change this to 8.3.261 as there is one feature used by foundry_install that has an impact on datestamps used in GDS and LEF files, and without which the version of open_pdks is usable but the files will differ from installation to installation due to changing datestamps.
